import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BeeReign",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function WithoutAuthLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-beereign_bg h-screen flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
